# Hibernate Settings
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

  # Enable H2 console, so we can view the data in web browser
  h2:
    console:
      enabled: true
      path: /h2-console

# BELOW database, we dont need to set them cuz spring boot
# see H2 dependency in out POM
#spring:
#  datasource:
#    url: jdbc:h2:mem:example
#    username: sa
#    password:
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect

# MONGO DEFAULT CONNECTION STRING NOT REQUIRED
# as spring will by default try to connect to it
  data:
    mongodb:
      host: 172.30.253.201  # hostname -I | cut -f 1 -d ' '
      port: 27017
      database: test
#      uri: mongodb://localhost:27017/test